package whois;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.4
 * 2021-12-21T22:01:34.331+01:00
 * Generated source version: 3.4.4
 *
 */
@WebService(targetNamespace = "http://milan.jovic.dmi.uns.ac.rs/", name = "WhoIsRemote")
@XmlSeeAlso({ObjectFactory.class})
public interface WhoIsRemote {

    @WebMethod
    @RequestWrapper(localName = "getWhoIsDescription", targetNamespace = "http://milan.jovic.dmi.uns.ac.rs/", className = "whois.GetWhoIsDescription")
    @ResponseWrapper(localName = "getWhoIsDescriptionResponse", targetNamespace = "http://milan.jovic.dmi.uns.ac.rs/", className = "whois.GetWhoIsDescriptionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getWhoIsDescription(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
