package geoip;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.4
 * 2021-12-21T22:03:43.919+01:00
 * Generated source version: 3.4.4
 *
 */
@WebService(targetNamespace = "http://milan.jovic.dmi.uns.ac.rs/", name = "GeoIPRemote")
@XmlSeeAlso({ObjectFactory.class})
public interface GeoIPRemote {

    @WebMethod
    @RequestWrapper(localName = "getGeoIPRemote", targetNamespace = "http://milan.jovic.dmi.uns.ac.rs/", className = "geoip.GetGeoIPRemote")
    @ResponseWrapper(localName = "getGeoIPRemoteResponse", targetNamespace = "http://milan.jovic.dmi.uns.ac.rs/", className = "geoip.GetGeoIPRemoteResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getGeoIPRemote(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
