package geoip;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.4.4
 * 2021-12-21T22:03:44.004+01:00
 * Generated source version: 3.4.4
 *
 */
@WebServiceClient(name = "GeoIPService",
                  wsdlLocation = "https://jovicev-ejb-servis.herokuapp.com/JovicevEJBServis-0.0.1-SNAPSHOT/GeoIP?wsdl",
                  targetNamespace = "http://milan.jovic.dmi.uns.ac.rs/")
public class GeoIPService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://milan.jovic.dmi.uns.ac.rs/", "GeoIPService");
    public final static QName GeoIPPort = new QName("http://milan.jovic.dmi.uns.ac.rs/", "GeoIPPort");
    static {
        URL url = null;
        try {
            url = new URL("https://jovicev-ejb-servis.herokuapp.com/JovicevEJBServis-0.0.1-SNAPSHOT/GeoIP?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(GeoIPService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "https://jovicev-ejb-servis.herokuapp.com/JovicevEJBServis-0.0.1-SNAPSHOT/GeoIP?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public GeoIPService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GeoIPService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GeoIPService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public GeoIPService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public GeoIPService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public GeoIPService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns GeoIPRemote
     */
    @WebEndpoint(name = "GeoIPPort")
    public GeoIPRemote getGeoIPPort() {
        return super.getPort(GeoIPPort, GeoIPRemote.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GeoIPRemote
     */
    @WebEndpoint(name = "GeoIPPort")
    public GeoIPRemote getGeoIPPort(WebServiceFeature... features) {
        return super.getPort(GeoIPPort, GeoIPRemote.class, features);
    }

}
